import { Award, BriefcaseBusiness, FolderKanban, Inbox, UserRound } from "lucide-react";
import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { defaultContent } from "@/lib/default-content";
import { AdminSidebar } from "@/components/admin/sidebar";
import { ItemShell } from "@/components/admin/item-form";
import { saveAchievement, saveCertification, saveProfile, saveProject, saveService, saveSkill, saveSocialLink, saveStat, saveTimeline, updateEnquiryStatus, uploadAsset } from "./actions";

export const dynamic = "force-dynamic";

export default async function AdminPage() {
  await requireAdmin();
  const [profile, stats, projects, skills, services, timeline, certifications, achievements, socialLinks, enquiries] = await Promise.all([
    prisma.profile.findUnique({ where: { id: 1 } }), prisma.siteStat.findMany({ orderBy: { sortOrder: "asc" } }), prisma.project.findMany({ orderBy: { sortOrder: "asc" } }), prisma.skill.findMany({ orderBy: { sortOrder: "asc" } }), prisma.service.findMany({ orderBy: { sortOrder: "asc" } }), prisma.timelineItem.findMany({ orderBy: { sortOrder: "asc" } }), prisma.certification.findMany({ orderBy: { sortOrder: "asc" } }), prisma.achievement.findMany({ orderBy: { sortOrder: "asc" } }), prisma.socialLink.findMany({ orderBy: { displayOrder: "asc" } }), prisma.enquiry.findMany({ orderBy: { createdAt: "desc" }, take: 50 })
  ]);
  const p = profile || defaultContent.profile;
  const experience = timeline.filter((item) => item.type === "experience");
  const education = timeline.filter((item) => item.type === "education");
  return <main className="min-h-screen bg-[#ebe9e2]"><AdminSidebar /><div className="p-5 sm:p-8 lg:ml-64 lg:p-10 xl:p-12">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Content management</p><h1 className="mt-2 font-display text-5xl font-semibold">Dashboard</h1></div><p className="text-sm text-ink/45">Changes appear on the public site immediately.</p></header>
    <section id="overview" className="mt-9 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[UserRound,"Profile","Complete"],[FolderKanban,"Projects",projects.length],[Award,"Achievements",achievements.length],[Inbox,"New enquiries",enquiries.filter((item) => item.status === "NEW").length]].map(([Icon,label,value]) => { const I=Icon as typeof UserRound; return <div className="admin-card flex items-center gap-4" key={label as string}><span className="grid size-11 place-items-center bg-blueprint text-copper"><I size={20} /></span><div><p className="text-xs text-ink/45">{label as string}</p><strong className="text-xl">{value as string | number}</strong></div></div>;})}</section>

    <AdminSection id="profile" title="Profile & contact" copy="The main identity and contact information shown throughout your website.">
      <form action={saveProfile} className="admin-card grid gap-5 sm:grid-cols-2">
        <Field label="Full name" name="name" value={p.name} /><Field label="Professional title" name="title" value={p.title} /><Field label="Hero heading" name="heroHeading" value={p.heroHeading} area wide /><Field label="Hero tagline" name="tagline" value={p.tagline} wide /><Field label="Professional summary" name="summary" value={p.summary} area wide /><Field label="About text" name="aboutText" value={p.aboutText} area wide /><Field label="Contact heading" name="contactHeading" value={p.contactHeading} /><Field label="Contact intro" name="contactIntro" value={p.contactIntro} area /><Field label="Email" name="email" value={p.email} type="email" /><Field label="Phone" name="phone" value={p.phone} /><Field label="Location" name="location" value={p.location} wide /><Field label="Availability" name="availability" value={p.availability} /><Field label="Years of experience" name="yearsExperience" value={p.yearsExperience} /><button className="admin-button sm:col-span-2">Save profile</button>
      </form>
      <div className="mt-5 grid gap-5 sm:grid-cols-2"><AssetForm kind="photo" label="Change profile photo" accept="image/jpeg,image/png,image/webp" current={p.photoUrl} /><AssetForm kind="cv" label="Upload new CV" accept="application/pdf,text/html,.docx" current={p.cvUrl} /></div>
    </AdminSection>

    <AdminSection id="contact-info" title="About, stats & contact info" copy="Manage the about statistics and contact text shown on the public website.">
      <div className="grid gap-5 xl:grid-cols-2">{stats.map(item => <ItemShell key={item.id} id={item.id} type="stat" title={`${item.value} ${item.label}`}><StatForm item={item} /></ItemShell>)}<ItemShell type="stat" title="Add stat"><StatForm /></ItemShell></div>
    </AdminSection>

    <AdminSection id="projects" title="Projects" copy="Use representative work now, then replace it with named projects and images as your portfolio grows.">
      <div className="grid gap-5 xl:grid-cols-2">{projects.map(item => <ItemShell key={item.id} id={item.id} type="project" title={item.title} subtitle={item.category}><ProjectForm item={item} /></ItemShell>)}<ItemShell type="project" title="Add project" subtitle="Create a new portfolio entry"><ProjectForm /></ItemShell></div>
    </AdminSection>

    <AdminSection id="expertise" title="Skills & services" copy="Control the expertise bars and the service cards on the public site.">
      <h3 className="mb-4 text-sm font-bold uppercase tracking-wider">Skills</h3><div className="grid gap-5 xl:grid-cols-2">{skills.map(item => <ItemShell key={item.id} id={item.id} type="skill" title={item.name} subtitle={item.category}><SkillForm item={item} /></ItemShell>)}<ItemShell type="skill" title="Add skill"><SkillForm /></ItemShell></div>
      <h3 className="mb-4 mt-10 text-sm font-bold uppercase tracking-wider">Services</h3><div className="grid gap-5 xl:grid-cols-2">{services.map(item => <ItemShell key={item.id} id={item.id} type="service" title={item.title}><ServiceForm item={item} /></ItemShell>)}<ItemShell type="service" title="Add service"><ServiceForm /></ItemShell></div>
    </AdminSection>

    <AdminSection id="experience" title="Experience" copy="Manage professional roles, employers, dates, and responsibilities.">
      <div className="grid gap-5 xl:grid-cols-2">{experience.map(item => <ItemShell key={item.id} id={item.id} type="timeline" title={item.title} subtitle={item.organization}><TimelineForm item={item} type="experience" /></ItemShell>)}<ItemShell type="timeline" title="Add experience"><TimelineForm type="experience" /></ItemShell></div>
    </AdminSection>

    <AdminSection id="education" title="Education" copy="Manage degrees, institutions, certifications, and academic details.">
      <div className="grid gap-5 xl:grid-cols-2">{education.map(item => <ItemShell key={item.id} id={item.id} type="timeline" title={item.title} subtitle={item.organization}><TimelineForm item={item} type="education" /></ItemShell>)}<ItemShell type="timeline" title="Add education"><TimelineForm type="education" /></ItemShell></div>
    </AdminSection>

    <AdminSection id="certifications" title="Certifications" copy="Manage certificates, training records, and credential links.">
      <div className="grid gap-5 xl:grid-cols-2">{certifications.map(item => <ItemShell key={item.id} id={item.id} type="certification" title={item.title} subtitle={item.issuer}><CertificationForm item={item} /></ItemShell>)}<ItemShell type="certification" title="Add certification"><CertificationForm /></ItemShell></div>
    </AdminSection>

    <AdminSection id="achievements" title="Achievements" copy="Show awards, academic highlights, milestones, and notable career accomplishments.">
      <div className="grid gap-5 xl:grid-cols-2">{achievements.map(item => <ItemShell key={item.id} id={item.id} type="achievement" title={item.title} subtitle={item.organization}><AchievementForm item={item} /></ItemShell>)}<ItemShell type="achievement" title="Add achievement"><AchievementForm /></ItemShell></div>
    </AdminSection>

    <AdminSection id="social-links" title="Social Links" copy="Manage the social icons shown in the contact section and footer.">
      <div className="grid gap-5 xl:grid-cols-2">{socialLinks.map(item => <ItemShell key={item.id} id={item.id} type="social" title={item.platform} subtitle={item.active ? "Active" : "Inactive"}><SocialForm item={item} /></ItemShell>)}<ItemShell type="social" title="Add social link"><SocialForm /></ItemShell></div>
    </AdminSection>

    <AdminSection id="enquiries" title="Enquiries" copy="Review saved contact form submissions and update their pipeline status.">
      <div className="grid gap-5">{enquiries.map(item => <div key={item.id} className="admin-card"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p className="eyebrow">{item.opportunityType}</p><h3 className="mt-2 text-xl font-bold">{item.fullName}</h3><p className="mt-1 text-sm text-ink/50">{item.email}{item.phone ? ` · ${item.phone}` : ""}</p><p className="mt-1 text-xs text-ink/40">{item.location || "No location"}{item.companyName ? ` · ${item.companyName}` : ""} · Prefers {item.preferredContactMethod} · {item.createdAt.toLocaleString()}</p></div><form action={updateEnquiryStatus} className="flex gap-2"><input type="hidden" name="id" value={item.id} /><select name="status" defaultValue={item.status} className="admin-input"><option value="NEW">New</option><option value="CONTACTED">Contacted</option><option value="IN_PROGRESS">In Progress</option><option value="CLOSED">Closed</option></select><button className="admin-button">Save</button></form></div><p className="mt-5 whitespace-pre-wrap border-t border-ink/10 pt-5 text-sm leading-7 text-ink/65">{item.message}</p></div>)}
      {!enquiries.length && <div className="admin-card text-sm text-ink/50">No enquiries yet.</div>}</div>
    </AdminSection>
  </div></main>;
}

function AdminSection({ id, title, copy, children }: { id: string; title: string; copy: string; children: React.ReactNode }) { return <section id={id} className="scroll-mt-8 pt-20"><div className="mb-7"><h2 className="font-display text-4xl font-semibold">{title}</h2><p className="mt-2 text-sm text-ink/50">{copy}</p></div>{children}</section>; }
function Field({ label, name, value = "", type = "text", area, wide, required = true }: { label: string; name: string; value?: string | number | null; type?: string; area?: boolean; wide?: boolean; required?: boolean }) { return <label className={`admin-label ${wide ? "sm:col-span-2" : ""}`}>{label}{area ? <textarea className="admin-input min-h-28 resize-y" name={name} defaultValue={value || ""} required={required} /> : <input className="admin-input" name={name} type={type} defaultValue={value || ""} required={required} />}</label>; }
function AssetForm({ kind,label,accept,current }: {kind:string;label:string;accept:string;current:string}) { return <form action={uploadAsset} className="admin-card"><input type="hidden" name="kind" value={kind} /><p className="font-bold">{label}</p><p className="mt-1 truncate text-xs text-ink/40">Current: {current}</p><input className="mt-5 block w-full text-sm" type="file" name="file" accept={accept} required /><button className="admin-button mt-5">Upload {kind}</button></form>; }

type ProjectItem = Awaited<ReturnType<typeof prisma.project.findFirst>>;
function ProjectForm({ item }: { item?: NonNullable<ProjectItem> }) { return <form action={saveProject} className="grid gap-4 sm:grid-cols-2">{item && <><input type="hidden" name="id" value={item.id} /><input type="hidden" name="existingImageUrl" value={item.imageUrl || ""} /></>}<Field label="Title" name="title" value={item?.title} /><Field label="Category" name="category" value={item?.category} /><Field label="Description" name="description" value={item?.description} area wide /><Field label="Location" name="location" value={item?.location} required={false} /><Field label="Year" name="year" value={item?.year} required={false} /><Field label="Duration" name="duration" value={item?.duration} required={false} /><Field label="Role" name="role" value={item?.role} required={false} /><Field label="Responsibilities" name="responsibilities" value={item?.responsibilities} area wide required={false} /><Field label="Technologies" name="technologies" value={item?.technologies} wide required={false} /><label className="admin-label sm:col-span-2">Project photo{item?.imageUrl && <img src={item.imageUrl} alt="Current project" className="mt-2 aspect-[16/7] w-full object-cover" />}<input className="admin-input" type="file" name="image" accept="image/jpeg,image/png,image/webp" /></label><Field label="Sort order" name="sortOrder" value={item?.sortOrder || 0} type="number" /><label className="flex items-end gap-2 pb-3 text-sm"><input type="checkbox" name="featured" defaultChecked={item?.featured} /> Featured</label><button className="admin-button sm:col-span-2">{item ? "Update" : "Add"} project</button></form>; }
type SkillItem = Awaited<ReturnType<typeof prisma.skill.findFirst>>;
function SkillForm({ item }: { item?: NonNullable<SkillItem> }) { return <form action={saveSkill} className="grid gap-4 sm:grid-cols-2">{item && <input type="hidden" name="id" value={item.id} />}<Field label="Skill" name="name" value={item?.name} /><Field label="Category" name="category" value={item?.category || "Technical"} /><label className="admin-label">Level<select className="admin-input" name="levelLabel" defaultValue={item?.levelLabel || "Advanced"}>{["Expert","Advanced","Intermediate"].map(x=><option key={x}>{x}</option>)}</select></label><Field label="Sort order" name="sortOrder" value={item?.sortOrder || 0} type="number" /><button className="admin-button sm:col-span-2">{item ? "Update" : "Add"} skill</button></form>; }
type CertificationItem = Awaited<ReturnType<typeof prisma.certification.findFirst>>;
function CertificationForm({ item }: { item?: NonNullable<CertificationItem> }) { return <form action={saveCertification} className="grid gap-4 sm:grid-cols-2">{item && <><input type="hidden" name="id" value={item.id} /><input type="hidden" name="existingImageUrl" value={item.imageUrl || ""} /></>}<Field label="Title" name="title" value={item?.title} /><Field label="Issuer" name="issuer" value={item?.issuer} /><Field label="Location" name="location" value={item?.location} required={false} /><Field label="Issued date" name="issuedDate" value={item?.issuedDate} required={false} /><Field label="Credential URL" name="credentialUrl" value={item?.credentialUrl} wide required={false} /><Field label="Description" name="description" value={item?.description} area wide /><label className="admin-label sm:col-span-2">Certification photo (optional){item?.imageUrl && <img src={item.imageUrl} alt="Current certification" className="mt-2 aspect-[16/7] w-full object-cover" />}<input className="admin-input" type="file" name="image" accept="image/jpeg,image/png,image/webp" /></label><Field label="Sort order" name="sortOrder" value={item?.sortOrder || 0} type="number" /><button className="admin-button sm:col-span-2">{item ? "Update" : "Add"} certification</button></form>; }
type AchievementItem = Awaited<ReturnType<typeof prisma.achievement.findFirst>>;
function AchievementForm({ item }: { item?: NonNullable<AchievementItem> }) { return <form action={saveAchievement} className="grid gap-4 sm:grid-cols-2">{item && <input type="hidden" name="id" value={item.id} />}<Field label="Title" name="title" value={item?.title} /><Field label="Organization" name="organization" value={item?.organization} required={false} /><Field label="Year" name="year" value={item?.year} required={false} /><Field label="Link URL" name="linkUrl" value={item?.linkUrl} required={false} /><Field label="Description" name="description" value={item?.description} area wide /><Field label="Sort order" name="sortOrder" value={item?.sortOrder || 0} type="number" /><button className="admin-button sm:col-span-2">{item ? "Update" : "Add"} achievement</button></form>; }
type StatItem = Awaited<ReturnType<typeof prisma.siteStat.findFirst>>;
function StatForm({ item }: { item?: NonNullable<StatItem> }) { return <form action={saveStat} className="grid gap-4 sm:grid-cols-2">{item && <input type="hidden" name="id" value={item.id} />}<Field label="Value" name="value" value={item?.value} /><Field label="Label" name="label" value={item?.label} /><Field label="Sort order" name="sortOrder" value={item?.sortOrder || 0} type="number" /><button className="admin-button sm:col-span-2">{item ? "Update" : "Add"} stat</button></form>; }
type SocialItem = Awaited<ReturnType<typeof prisma.socialLink.findFirst>>;
function SocialForm({ item }: { item?: NonNullable<SocialItem> }) { return <form action={saveSocialLink} className="grid gap-4 sm:grid-cols-2">{item && <input type="hidden" name="id" value={item.id} />}<Field label="Platform name" name="platform" value={item?.platform} /><Field label="URL" name="url" value={item?.url} /><label className="admin-label">Icon name<select className="admin-input" name="icon" defaultValue={item?.icon || "Globe"}>{["Globe","Linkedin","Facebook","Instagram","Twitter","Github","Mail","Phone","ArrowUpRight"].map(x=><option key={x}>{x}</option>)}</select></label><Field label="Display order" name="displayOrder" value={item?.displayOrder || 0} type="number" /><label className="flex items-end gap-2 pb-3 text-sm"><input type="checkbox" name="active" defaultChecked={item?.active ?? true} /> Active</label><button className="admin-button sm:col-span-2">{item ? "Update" : "Add"} social link</button></form>; }
type ServiceItem = Awaited<ReturnType<typeof prisma.service.findFirst>>;
function ServiceForm({ item }: { item?: NonNullable<ServiceItem> }) { return <form action={saveService} className="grid gap-4 sm:grid-cols-2">{item && <input type="hidden" name="id" value={item.id} />}<Field label="Title" name="title" value={item?.title} /><label className="admin-label">Icon<select className="admin-input" name="icon" defaultValue={item?.icon || "Building2"}>{["Building2","HardHat","ClipboardCheck","DraftingCompass"].map(x=><option key={x}>{x}</option>)}</select></label><Field label="Description" name="description" value={item?.description} area wide /><Field label="Sort order" name="sortOrder" value={item?.sortOrder || 0} type="number" /><button className="admin-button sm:col-span-2">{item ? "Update" : "Add"} service</button></form>; }
type Timeline = Awaited<ReturnType<typeof prisma.timelineItem.findFirst>>;
function TimelineForm({ item, type }: { item?: NonNullable<Timeline>; type: "experience" | "education" }) { const isExperience = type === "experience"; return <form action={saveTimeline} className="grid gap-4 sm:grid-cols-2">{item && <input type="hidden" name="id" value={item.id} />}<input type="hidden" name="type" value={type} /><Field label={isExperience ? "Role" : "Degree / certification"} name="title" value={item?.title} /><Field label={isExperience ? "Employer" : "Institution"} name="organization" value={item?.organization} /><Field label="Location" name="location" value={item?.location} /><Field label="Start date" name="startDate" value={item?.startDate} /><Field label="End date" name="endDate" value={item?.endDate} /><Field label={isExperience ? "Responsibilities" : "Academic details"} name="description" value={item?.description} area wide /><Field label="Sort order" name="sortOrder" value={item?.sortOrder || 0} type="number" /><button className="admin-button sm:col-span-2">{item ? "Update" : "Add"} {type}</button></form>; }
